### ISSUE TITLE
mimic数据集好像无法运行 

### ISSUE THREAD

**Issue by SuiYuan520** [guyulongcs/AAAI2021_ANPP#1]
mimic数据集可以正常训练，但是在Evaluation on testing data:的时候报错：numpy.AxisError: axis2: axis 1 is out of bounds for array of dimension 1
    调试发现all_time_preds ， all_event_preds 都为空。其它数据集都能正常运行，就是mimic数据集有这个问题。

**Comment by guyulongcs** [comment]
No problem.
